# https://docs.docker.com/compose/compose-file/
version: "3.8"
services: 
    app:
        container_name: yardk-sails
        # restart: always
        restart: "no"
        build: .
        ports: 
            - "9000:1337"
        volumes:
<<<<<<< HEAD
            - ./:/app
        environment:
            MONGO_HOST: mongo
=======
            - .:/usr/app/
            - /usr/app/node_modules
        #     - .:/app
        # environment: 
        #     NODE_ENV: production
>>>>>>> maps volumes for better developer exp.
        links:
            - redis
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        ports: 
            - "27017:27017"
    redis:
        container_name: redis
        image: redis
        ports:
            - "6379:6379"